version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      golang: 1.16
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install
      - cd ../backend
      - go mod download
  build:
    commands:
      - echo "Building the application..."
      - cd ../frontend
      - npm run build
      - cd ../backend
      - GOOS=linux GOARCH=amd64 go build -o bin/sync-scribe
  post_build:
    commands:
      - echo "Copying frontend build to backend directory..."
      - cp -r ../frontend/build ./frontend
artifacts:
  files:
    - backend/**/*
  name: sync-scribe-$(date +%Y-%m-%d)