version: 0.2

phases:
  install:
    runtime-versions:
      golang: '1.21'
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix frontend
      - echo "Pre-build steps..."
  build:
    commands:
      - mkdir /etc/systemd/system/nginx.service.d
      - echo "Building the Go application..."
      - go build -o SyncScribeApp ./cmd/syncscribe
      - echo "Running Go tests..."
      - go test ./...
      - echo "Building the React frontend..."
      - npm run build --prefix frontend
  post_build:
    commands:
      - echo "List directory content to debug"
      - ls -la
artifacts:
  files:
    - SyncScribeApp
    - Procfile
    - go.mod
    - go.sum
    - frontend/build/**/*

