version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      golang: 1.20
    commands:
    - export NODE_OPTIONS=--openssl-legacy-provider
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install
      - cd ../backend
      - go mod download
  build:
    commands:
      - echo "Building the application..."
      - cd ../frontend
      - npm run build
      - cd ../backend
      - GOOS=linux GOARCH=amd64 go build -o bin/SyncScribe
  post_build:
    commands:
      - echo "Copying frontend build to frontend directory..."
      - cp -r ../frontend/build/* ../frontend/
      - echo "Copying Procfile to the root directory..."
      - cp Procfile ../
      - echo "Debug Printing directory structure from root..."
      - ls -lR ../

artifacts:
  files:
    - Procfile
    - bin/SyncScribe
    - backend/**/*
    - frontend/**/*
  name: sync-scribe-$(date +%Y-%m-%d)