version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
      nodejs: 18
    commands:
      - echo "Building Go backend..."
      - cd backend
      - go build -o main
      - echo "Packaging backend artifacts..."
      - zip ../backend-artifact.zip main
      - cd ..
      - echo "Building React frontend..."
      - cd frontend
      - npm install
      - npm run build
      - echo "Packaging frontend artifacts..."
      - cd build
      - zip -r ../../frontend-artifact.zip *
      - cd ../..
  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - aws elasticbeanstalk update-environment --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label "$(date +%Y-%m-%d-%H-%M-%S)"

artifacts:
  files:
    - backend-artifact.zip
    - frontend-artifact.zip


artifacts:
  files:
    - Dockerrun.aws.json
    - backend/Dockerfile
    - frontend/Dockerfile
  name: sync-scribe-$(date +%Y-%m-%d)