version: 0.2

phases:
  install:
    runtime-versions:
      golang: '1.21'
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix frontend
      - echo "Dependencies installed."
      - echo "Pre-build steps..."

  build:
    commands:
      - echo "Building the Go application..."
      - go build -o SyncScribeApp ./cmd/syncscribe
      - echo "Go application built."
      - echo "Running Go tests..."
      - go test ./...
      - echo "Go tests completed."
      - echo "Building the React frontend..."
      - npm run build --prefix frontend
      - echo "React frontend built."

  post_build:
    commands:
      - echo "Making start script executable..."
      - chmod +x start_app.sh
      - echo "List directory content to debug"
      - ls -la
      
artifacts:
  files:
    - SyncScribeApp
    - Procfile
    - start_app.sh
    - go.mod
    - go.sum
    - frontend/build/**/*
    - .ebextensions/**/*