version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - pip install yq
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(yq .aws.account_id aws-config.yml)
      - REGION=$(yq .aws.region aws-config.yml)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t syncscribe-backend backend/
      - docker build -t syncscribe-frontend frontend/
      - echo "Tagging Docker images..."
      - docker tag syncscribe-backend:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/syncscribe-backend:latest
      - docker tag syncscribe-frontend:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/syncscribe-frontend:latest
  post_build:
    commands:
      - echo "Pushing Docker images to Amazon ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/syncscribe-backend:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/syncscribe-frontend:latest

artifacts:
  files:
    - docker-compose.yml
    - backend/Dockerfile
    - frontend/Dockerfile
  name: sync-scribe-$(date +%Y-%m-%d)