version: 0.2

phases:
  install:
    runtime-versions:
      golang: '1.21' # Specify the Go version matching your development environment
    commands:
      - echo "Installing dependencies..."
      # Include any other dependency installation
  pre_build:
    commands:
      - echo "Pre-build steps..."
  build:
    commands:
      - echo "Building the application..."
      - go build -o SyncScribeApp ./cmd/syncscribe
      - echo "Running tests..."
      - go test ./...
  post_build:
    commands:
      - echo "Post-build steps..."
      # Include any commands to package your application for deployment, if necessary
artifacts:
  files:
    - SyncScribeApp
    # Specify additional files or directories needed for your deployment

